<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Functions (Good)</span></div>

## 1 Check, balances and contingencies

In [1]:
import numpy as np

### 1.1 assert

In [2]:
# synthax
# assert condition-to-check, message
## assert stops the flow if the condition fails

In [3]:
x = 10
assert x >= 0, "x is becoming negative!"
print(x)

10


In [4]:
x = -1
assert x >= 0, "x is becoming negative!"
print(x)

AssertionError: x is becoming negative!

### 1.2 try-except

In [5]:
# things gg wrong = exceptions
# exception left unhandled will halt the flow of the programme

In [6]:
number=input("Give me a number and I will calculate its square.")
square=int(number)**2       # converts English to number
print(f'The square of {number} is {square}!')

Give me a number and I will calculate its square.5
The square of 5 is 25!


In [7]:
number=input("Give me a number and I will calculate its square.")
square=int(number)**2       # converts English to number
print(f'The square of {number} is {square}!')

Give me a number and I will calculate its square.five


ValueError: invalid literal for int() with base 10: 'five'

In [8]:
try:
    number=input("Give me a number and I will calculate its square.")
    square=int(number)**2
    print(f'The square of {number} is {square}!')
except:
    print(f"Oh oh! I cannot square {number}!")

Give me a number and I will calculate its square.five
Oh oh! I cannot square five!


## 2 Some loose ends

### 2.1 Positional, keyword and default arguments

In [9]:
def funny_add(a, b, c=1):   
    return a + 10*b + 100*c
funny_add(1, 2, 3)  #order is impt i.e., a=1, b=2, c=3

# default value for c is 1 i.e. if no value is input, c=1

321

In [10]:
funny_add(1,2)

121

In [11]:
funny_add(c=3, a=1, b=2) # order does not matter

321

In [12]:
funny_add(a=2, 1)         # Won't work.
                          # Keywords cannot be followed by 
                          # positional
# Python cannot unambiguously figure out what the position of 1 is

SyntaxError: positional argument follows keyword argument (702417007.py, line 1)

### 2.2 Docstrings

In [13]:
def funny_add(a, b, c=1):
    '''
    A test function to demonstrate how 
    positional, keyword and default arguments 
    work.
    '''
    return a + 10*b + 100*c
# docstring needs to be sandwiched btwn '''.....'''

In [14]:
help(funny_add)

Help on function funny_add in module __main__:

funny_add(a, b, c=1)
    A test function to demonstrate how 
    positional, keyword and default arguments 
    work.



### 2.3 Function are first class citizens

In [15]:
#  u can pass a fn as an argument to another fn

def my_function(angle, trig_function):
        return trig_function(angle)

my_function(np.pi/2, np.sin)

1.0

In [16]:
my_function(np.pi/2, np.cos)        

6.123233995736766e-17

In [17]:
my_function(np.pi/2, lambda x: np.cos(2*x))

# reminder: lambda function always returns 
# the value of the last statement

-1.0

### 2.4 More unpacking

In [18]:
x, y, z = [1, 2, 3]
print(x, y, z)

1 2 3


In [19]:
x, y, z = np.array([1, 2, 3])
print(x, y, z)

1 2 3


In [20]:
x, *y, z = np.array([1, 2, 3, 4, 5])
print(x, y, z)
# *y = variable values of y, since x & z only has 1 value,
# the remaining values are assigned to y

1 [2, 3, 4] 5


In [22]:
x, y, *z = np.array([1, 2, 3, 4, 5])
print(x, y, z)

1 2 [3, 4, 5]


In [23]:
x, *_, y = [1, 2, 3, 4, 5]
print(x, y)

1 5


## Exercise 1 :  A better calculator I

In [74]:
x=np.array([0, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])

In [75]:
def add(x,y):
    return x+y
add(x,y)

array([ 64, 100, 100, 100, 100])

In [76]:
def subtract(x,y):
    return x-y
subtract(x,y)

array([-64, -32, -12,  52, -46])

In [77]:
def multiply(x,y):
    return x*y
multiply(x,y)

array([   0, 2244, 2464, 1824, 1971])

In [87]:
def divide(x,y):
    y=np.array(y)
    assert (y!=0).all(), "cannot divide by zero" # checks if any of them are zero
    return x/y
 # assert first then return

divide(x,y)

array([0.        , 0.51515152, 0.78571429, 3.16666667, 0.36986301])

In [88]:
divide(2,0)

AssertionError: cannot divide by zero

In [89]:
divide(y,x)

AssertionError: cannot divide by zero

## Exercise 2 :  A better calculator II

In [99]:
x=np.array([0, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])

In [121]:
def add(x,y):
    return x+y

def subtract(x,y):
    return x-y

def multiply(x,y):
    return x*y

def divide(x,y):
    try:
        assert (y!=0).all(), 'abcd'
        return x/y
    except:
        print(f'cannot divide') # this will override the 'abcd' above

In [118]:
add(x,y)

array([ 64, 100, 100, 100, 100])

In [119]:
subtract(x,y)

array([-64, -32, -12,  52, -46])

In [120]:
multiply(x,y)

array([   0, 2244, 2464, 1824, 1971])

In [114]:
divide(y,x)

cannot divide
