<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Functions (Need)</span></div>

In [1]:
import numpy as np

## 1 User defined functions

### 1.1 Named functions that return

In [2]:
def greeting(name):
    if name == 'Pikachu':
        return 'Hello Pikachu! So, nice to meet you!'
    else:
        return f'Hello {name}!'
# function name is **greeting** which accepts 1 argument **name**

In [3]:
greeting("Snorlax")

'Hello Snorlax!'

In [4]:
greeting(name='Squirtle')

'Hello Squirtle!'

In [5]:
greet = greeting(name='Charmander')
print(greet)
print(greeting(name='Squirtle'))

Hello Charmander!
Hello Squirtle!


In [6]:
def basic_stats(numbers):
    np_numbers=np.array(numbers)
    return np_numbers.min(), np_numbers.max(), np_numbers.mean()

# can use funciton ony w/in a function

In [7]:
list_min, list_max, list_mean = basic_stats([1, 2, 3, 4, 5])
print(list_min)
print(list_max)
print(list_mean)

1
5
3.0


### 1.2 Named functions that don’t return

### 1.3 Anonymous functions

In [8]:
my_short_function = lambda name: f"Hello {name}!"
my_short_function(name="Pikachu")

'Hello Pikachu!'

In [9]:
numbers=[[9, 0, 10],
         [8, 1, 11],
         [7, 2, 12],
         [6, 3, 13],
         [5, 4, 14],
         [4, 5, 15],
         [3, 6, 16],
         [2, 7, 17],
         [1, 8, 18],
         [0, 9, 19]]

sorted(numbers)      # sort by comparing the default key 
                     # (i.e. the 1st element) 

[[0, 9, 19],
 [1, 8, 18],
 [2, 7, 17],
 [3, 6, 16],
 [4, 5, 15],
 [5, 4, 14],
 [6, 3, 13],
 [7, 2, 12],
 [8, 1, 11],
 [9, 0, 10]]

In [10]:
sorted(numbers, key=lambda x: x[1]) 

# sort by comparing a custom key that uses the 2nd element
# lambda fn always returns the value of the last statement

[[9, 0, 10],
 [8, 1, 11],
 [7, 2, 12],
 [6, 3, 13],
 [5, 4, 14],
 [4, 5, 15],
 [3, 6, 16],
 [2, 7, 17],
 [1, 8, 18],
 [0, 9, 19]]

In [11]:
sorted(numbers, key=lambda x: sum(x))  
# sort by comparing a custom key that uses
# the sum of the elements (ascending order)

[[9, 0, 10],
 [8, 1, 11],
 [7, 2, 12],
 [6, 3, 13],
 [5, 4, 14],
 [4, 5, 15],
 [3, 6, 16],
 [2, 7, 17],
 [1, 8, 18],
 [0, 9, 19]]

### 1.4 Optional arguments

In [12]:
def greeting(name='Lilo'):
    if name == 'Stitch':
        return 'Hello Stitch! So, nice to meet you!'
    else:
        return f'Hello {name}!'

greeting()

'Hello Lilo!'

In [13]:
greeting('Stitch')

'Hello Stitch! So, nice to meet you!'

In [14]:
?print

In [15]:
print('Ohana', 'means', 'family.')                
print('Ohana', 'means', 'family.', sep='---')  

# Just for comparison

Ohana means family.
Ohana---means---family.


## 2 The importance of functions?

### 2.1 An argument for functions

In [16]:

# Your code here


### 2.2 A word of caution

In [17]:

# Your code here


## Exercise 1 :  Do you know why?

In [18]:
def greeting(name):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    return f'Hello {name}!'
greeting('Robin')

'Hello Robin!'

The return statement runs will stop the current function gretting(). Hence, there is no need for an else statement as if the 'if' condition is not met, it will automatically run the code after it.

## Exercise 2 :  Calculator functions

In [15]:
x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])

In [20]:
def add(x,y):  # x and y here are just local variables, they dont refer to the x & y in the cell above
    return x+y

In [21]:
add(x,y)

array([100, 100, 100, 100, 100])

In [22]:
add(y[4], x[1])

107

In [23]:
def subtract(x,y):
    return x-y

In [24]:
subtract(x,y)

array([-28, -32, -12,  52, -46])

In [25]:
subtract(y,x)

array([ 28,  32,  12, -52,  46])

In [26]:
subtract(x[3],y[4])

3

In [27]:
def multiply(x,y):
    return x*y

In [28]:
multiply(x,y)

array([2304, 2244, 2464, 1824, 1971])

In [29]:
multiply(x[0],y[3])

864

In [12]:
# this is wrong
def divide(x,y):
    y= np.array(y) # converts y into a numpy array
    if  (y==0).all():  
        return f'error'
    return x/y
# 

In [16]:
# correction for above
def divide(x,y):
    y = np.array(y)
    if (y==0).any() == True:
        return f'error'
    return x/y    

divide(x,y)

array([0.5625    , 0.51515152, 0.78571429, 3.16666667, 0.36986301])

In [17]:
x = np.array([1,2,3])
y =np.array([0,0,0])

divide(x,y)

'error'

In [6]:
1 == True # any number other than 1 is false

True

In [31]:
divide (6,3) # just to check if the function works

2.0

In [32]:
divide(3,0)  # just to check if the function works

'error'

In [33]:
a = [0, 1, 2]
b = [2, 0, 4]
divide(a,b) # just to check if the function works in an array

'error'

In [34]:
arr_1 = np.array([0, 0])
arr_2 = np.array([0, 1])
arr_3 = np.array([1, 1])

print(f'arr_1: {arr_1.any(), arr_1.all()}')
print(f'arr_2: {arr_2.any(), arr_2.all()}')
print(f'arr_3: {arr_3.any(), arr_3.all()}')

# mentor showed how .any and .all works

arr_1: (False, False)
arr_2: (True, False)
arr_3: (True, True)


In [35]:
divide(x,y)

array([0.5625    , 0.51515152, 0.78571429, 3.16666667, 0.36986301])

## Exercise 3 :  max_info() with NumPy

In [36]:
numbers = [40, 27, 83, 44, 74, 51, 76, 77, 10, 49]

In [37]:
def max_info(x):
    return np.max(np.array(x)), np.argmax(np.array(x))

In [38]:
max_info(numbers)

(83, 2)