<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

In [1]:
import numpy as np

## 1 Subsetting: Indexing and Slicing

### 1.1 Indexing & Slicing 1D (Lists & Arrays)

In [2]:
# Subsetting: ‘select’.
# Indexing: select one element
# Slicing: select a range of elements

py_list=['red', 'orange', 'yellow', 'green', 'blue',
        'indigo', 'violet', 'white', 'black', 'pink']
np_array = np.array(py_list)
x = np_array

In [3]:
print(x[0]) # 1st element
print(x[-1]) # last element

# to index 0-3
print(x[0:4]) # gives 4-0= 4 elements
print(x[:4])  # gives first for elements

# to index 3-8
print(x[3:9]) # gives 9-3= 6 elements

# to index 1-5 in steps of 2 (every 2 elements)
print(x[1:6:2]) # gives every other element of 6-1 = 5
print(x[0:8:3])

# to index 3 to the end
print(x[3:]) # gives len(x)-3 = 10-3 = 7

# index 5-3 in reverse
print(x[5:2:-1]) # gives 3 elements
print(x[5:2:-2]) # in steps of two but reverse

# reverse whole list
print(x[::-1])

red
pink
['red' 'orange' 'yellow' 'green']
['red' 'orange' 'yellow' 'green']
['green' 'blue' 'indigo' 'violet' 'white' 'black']
['orange' 'green' 'indigo']
['red' 'green' 'violet']
['green' 'blue' 'indigo' 'violet' 'white' 'black' 'pink']
['indigo' 'blue' 'green']
['indigo' 'green']
['pink' 'black' 'white' 'violet' 'indigo' 'blue' 'green' 'yellow' 'orange'
 'red']


### 1.2 Subsetting by masking (Arrays only)

In [4]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 4
print(my_mask)

[False False False False  True  True  True  True  True  True]


In [5]:
print(np_array > 4) # same

[False False False False  True  True  True  True  True  True]


In [6]:
np_array[my_mask] # masking only shows the TRUE subset 
#only works with numpy arrays

array([ 5,  6,  7,  8,  9, 10])

In [7]:
np_array[np_array > 4] # works too!

array([ 5,  6,  7,  8,  9, 10])

In [8]:
# ~ = bitwise not operator,, basically just means NO
np_array[~(np_array > 4)]  # tldr: inverse the selection

array([1, 2, 3, 4])

In [9]:
# & means and (duh hahaha)
np_array[(np_array > 4) & (np_array <7)]

array([5, 6])

In [10]:
np_array[(np_array > 4) & (np_array > 7)] 
# true for both > 4 AND > 7

array([ 8,  9, 10])

In [11]:
np_array[~((np_array > 4) & (np_array <7))] 
# ~ bracket must encompass the whole selection that you want to inverse

array([ 1,  2,  3,  4,  7,  8,  9, 10])

In [12]:
np_array[(np_array < 3) | (np_array > 8)] 
# | means or ,,, true for < 3 OR > 8 i.e need to fulfill one req only

array([ 1,  2,  9, 10])

### 1.3 Indexing & Slicing 2D Lists

In [13]:
py_list_2d = [[1, "Ant"], [2, "Bear"], [3, "Cat"], [4, "Dog"],
              [5, "Eagle"], [6, "Frog"], [7, "Giraffe"], [8, "Hippo"],
              [9, "Iguana"], [10, "Jaguar"]]

In [14]:
py_list_2d[6] # element at postion 7 (index 6)

[7, 'Giraffe']

In [15]:
py_list_2d[7][0]     # FIRST element at position 8 (index 7)

8

In [16]:
py_list_2d[:3]  #first 3 elements

[[1, 'Ant'], [2, 'Bear'], [3, 'Cat']]

In [17]:
py_list_2d[:3][0] # first elements from the selected list

[1, 'Ant']

In [18]:
py_list_2d[4:7][0] 
# before :, first element index 4, after : second element index 7

[5, 'Eagle']

In [19]:
py_list_2d[5:] # elements from index 5 onwards

[[6, 'Frog'], [7, 'Giraffe'], [8, 'Hippo'], [9, 'Iguana'], [10, 'Jaguar']]

### 1.4 Indexing & Slicing 2D Arrays

In [20]:
np_array_2d = np.array([[1, "Ant"], [2, "Bear"], [3, "Cat"], [4, "Dog"],
                       [5, "Eagle"], [6, "Frog"], [7, "Giraffe"], [8, "Hippo"],
                       [9, "Iguana"], [10, "Jaguar"]])

In [21]:
np_array_2d[5] 

array(['6', 'Frog'], dtype='<U11')

In [22]:
np_array_2d[5,0] 
#np_array use only 1 pair of [] while py_list use [][]

'6'

In [23]:
np_array_2d[:3]

array([['1', 'Ant'],
       ['2', 'Bear'],
       ['3', 'Cat']], dtype='<U11')

In [24]:
np_array_2d[:3,0] 
# np shows first elements of the first 3 postions

array(['1', '2', '3'], dtype='<U11')

In [25]:
np_array_2d[3:6, 0]
# np shows first elements on postions 4 - 6

array(['4', '5', '6'], dtype='<U11')

In [26]:
np_array_2d[3:6, 1] 
# shows second elements on positions 4 - 6

array(['Dog', 'Eagle', 'Frog'], dtype='<U11')

In [27]:
np_array_2d[5:]
#elements from postion 6 onwards

array([['6', 'Frog'],
       ['7', 'Giraffe'],
       ['8', 'Hippo'],
       ['9', 'Iguana'],
       ['10', 'Jaguar']], dtype='<U11')

In [28]:
print(np_array_2d[:, 0])
print(np_array_2d[:, 1])

['1' '2' '3' '4' '5' '6' '7' '8' '9' '10']
['Ant' 'Bear' 'Cat' 'Dog' 'Eagle' 'Frog' 'Giraffe' 'Hippo' 'Iguana'
 'Jaguar']


### 1.5 Growing lists

In [29]:
x=['frog']*5
x            

['frog', 'frog', 'frog', 'frog', 'frog']

In [30]:
x=[2]*6
x

[2, 2, 2, 2, 2, 2]

In [31]:
x=[2]
x = x + [1]   # !! does not add 1 to original value of 2
x = x + [2]   # only grows the list
x = x + [3]
x = x + [4]
x

[2, 1, 2, 3, 4]

In [32]:
x=[2]
x+= [1]
x+= [2]
x+= [3]
x+= [4]
x
# works the same

[2, 1, 2, 3, 4]

In [33]:
x=[2]
x+= [1, 2, 3, 4]
x
# do it all in one go

[2, 1, 2, 3, 4]

In [34]:
x=[2]
x= [1, 2, 3, 4] + x
x

[1, 2, 3, 4, 2]

In [35]:
x=[2]
x.append(1)
x.append(2)
x.append(3)
x.append(4)
x

[2, 1, 2, 3, 4]

## 2 Some loose ends

### 2.1 Tuples

In [36]:
#define tuple first
a=(1,2,3)

In [37]:
#access its data
print(a[0])
print(a[2])

# cannot change the data
# i.e. a[0] = -1  --> wont work
# a[0] += [10]   --> wont work

1
3


### 2.2 Be VERY careful when copying

In [38]:
# correct way of copying list

x=['frog','froggo','froggy']
y=x.copy()
z=x.copy()

In [39]:
y

['frog', 'froggo', 'froggy']

In [40]:
z

['frog', 'froggo', 'froggy']

## Exercise 1 :  Total recall?

1. subsetting: select
1. indexing: select one element
1. slicing: select range of elements
1. masking: select True only

## Exercise 2 :  Show me the ‘odd’ letters

In [41]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])
# instructions:
# Use masking to subset the letters that correspond to the odd numbers 
# I.e. get the result [A, C, E, G, I]


In [42]:
np_array_2d[:,0].astype(int)

# astype provides the capability to 
# convert any suitable existing column to categorical type

array([ 1,  3,  2,  4,  5,  7,  6,  8, 10,  9])

In [43]:
np_array_2d[:,0].astype(int)%2

array([1, 1, 0, 0, 1, 1, 0, 0, 0, 1], dtype=int32)

In [44]:
my_mask = np_array_2d[:,0].astype(int)%2 > 0
print(my_mask)

[ True  True False False  True  True False False False  True]


In [45]:
np_array_2d[my_mask, 1]

array(['A', 'C', 'E', 'G', 'I'], dtype='<U11')

In [46]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])
np_array_2d[:,0].astype(int)
np_array_2d[:,0].astype(int)%2
my_mask = np_array_2d[:,0].astype(int)%2 > 0
print(my_mask)
np_array_2d[my_mask, 1]

[ True  True False False  True  True False False False  True]


array(['A', 'C', 'E', 'G', 'I'], dtype='<U11')