<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

## 1 Lists, Arrays & Dictionaries

### 1.1 Let’s compare

In [1]:
import numpy as np

In [2]:
# python list

py_atla_names = ['Aang', 'Katara', 'Toph', 'Zuko']
py_bender = ['Air', 'Water', 'Earth', 'Fire']

In [3]:
# numpy arrays

np_atla_names = np.array(['Aang', 'Katara', 'Toph', 'Zuko'])
np_bender = np.array(['Air', 'Water', 'Earth', 'Fire'])

In [4]:
# dictionary
bender_info = {'Aang': 'Air',
              'Katara': 'Water',
              'Toph': 'Earth',
              'Zuko': 'Fire'
              }

### 1.2 Accessing data from a list (or array)

In [5]:
# python starts counting at 0
print(py_atla_names[2])
print(py_bender[2])      # forward indexing - need to know size
print(py_atla_names[-1]) # reverse indexing - no need to know size
print(py_atla_names[-3])

Toph
Earth
Zuko
Katara


### 1.3 Accessing data from a dictionary

In [6]:
print(bender_info['Katara'])

Water


In [7]:
bender_info.keys()

dict_keys(['Aang', 'Katara', 'Toph', 'Zuko'])

In [8]:
bender_info.values() # list of 'definitions'

dict_values(['Air', 'Water', 'Earth', 'Fire'])

### 1.4 Higher dimensional lists

In [9]:
py_bender_info = [['Aang', 'Air'],
                   ['Katara', 'Water'],
                   ['Toph', 'Earth'],
                   ['Zuko', 'Fire']]

## 2 Lists vs. Arrays

### 2.1 Size

In [10]:
# setup
py_list_2d = [['Aang', 'Air'], ['Katara', 'Water'], ['Toph', 'Earth'],
              ['Zuko', 'Fire']]

np_array_2d = np.array(py_list_2d)    # np.array converts the python list to a numpy array
len(py_list_2d)  # len fn to tell list size

4

In [11]:
np_array_2d.shape
# shape is not a function
# it is a property or attribute of the NumPy array

(4, 2)

### 2.2 Arrays are fussy about type

In [12]:
# arrays like having a single data type
# lists are more accommodating

In [13]:
py_list = [1, 1.5, 'A']
np.array(py_list)


# NumPy arrays tolerate only a single type
# numbers are converted to English (' ') 
# when we create the NumPy array

# can easily change type (typecast) using the ‘hidden’ function astypes()

array(['1', '1.5', 'A'], dtype='<U32')

### 2.3 Adding a number

In [14]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list) 

In [15]:
# py_list + 10 -- this wont work!

np_array + 10 # adds 10 to each value in the list

array([11, 12, 13, 14, 15])

### 2.4 Adding another list

In [16]:
# set up
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [19, 20, 21, 22, 23]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

In [17]:
py_list_1 + py_list_2   # adds the lists tgt - just makes it longer

[1, 2, 3, 4, 5, 19, 20, 21, 22, 23]

In [18]:
np_array_1 + np_array_2   # adds the values in the lists

array([20, 22, 24, 26, 28])

### 2.5 Multiplying by a Number

In [19]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [20]:
py_list*2  # just repeat the values in the list

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [21]:
np_array*6 # multiply the values in the array by 6

array([ 6, 12, 18, 24, 30])

### 2.6 Squaring

In [22]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)
# py_list**2 --> Won't work
np_array**2  # squares the values in the array

array([ 1,  4,  9, 16, 25])

### 2.7 Asking questions

In [23]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [24]:
# list
py_list == 3 # the qn is; is the list = 3, the answer will always be false bc a list cannot = number

False

In [25]:
np_array == 2

array([False,  True, False, False, False])

In [26]:
np_array < 3  

array([ True,  True, False, False, False])

### 2.8 Mathematics

In [27]:
py_list = [1, 2, 3, 4, 5, 6, 7]
np_array = np.array(py_list)         

In [28]:
#py_list

print(sum(py_list)) # sum() -- sum of all values in the list
print(max(py_list)) # max() -- max value in the list
print(min(py_list)) # min() -- min value in list

# py_list.sum()   # Won't work!

28
7
1


In [29]:
#np_array

print(np_array.sum())
print(np_array.mean())
print(np_array.min())
print(np_array.max())

28
4.0
1
7


## Exercise 1 :  Total recall?

Similarities btwn list & arrays
1. they're both technically just lists, meaning they store information in a list
1. they both can be indexed (uses 0 based index)

Differences btwn list & arrays
1. when adding/multiplying, a list just grows longer but an array would add/multiply the values in the array
1. arrays can only tolerate a single type while lists are more accommodating

What is a dictionary?
- 'list' that holds a key with an associated 'definition'  

## Exercise 2 :  Index me

In [30]:
py_list = ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]
                    # Prints 'a1'
                    # Prints 'c3'
                    # Prints 'e5'
                    # Prints 'g7'
print(py_list[0], py_list[2],py_list[4],py_list[6],py_list[8])   # Prints 'i9'

a1 c3 e5 g7 i9


## Exercise 3 :  Capitalise Heros

In [31]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

superhero_info['Tony Stark'] = superhero_info['Tony Stark'].upper()     
superhero_info['Natasha Romanoff'] = superhero_info['Natasha Romanoff'].upper()
superhero_info['Stephen Strange'] = superhero_info['Stephen Strange'].upper()
print(superhero_info)

{'Natasha Romanoff': 'BLACK WIDOW', 'Tony Stark': 'IRON MAN', 'Stephen Strange': 'DOCTOR STRANGE'}


## Exercise 4 :  How many ones

In [32]:
numbers=[45, 60, 1, 30, 96, 1, 96, 57, 16, 1,
        99, 62, 86, 43, 42, 60, 59, 1, 1, 35,
        83, 47, 34, 28, 68, 23, 22, 92, 1, 79,
        1, 29, 94, 72, 46, 47, 1, 74, 32, 20,
        8, 37, 35, 1, 89, 29, 86, 19, 43, 61]    
np_array = np.array(numbers)

In [33]:
x = np_array == 1 
x.sum()

9

In [34]:
sum(np_array == 1) # this works too!

9